
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_api
    username: root
    password: password

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/

logging:
  level:
    org.springframework.security: DEBUG
